/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as EhsRouteImport } from './routes/ehs'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as LabourRouteImport } from './routes/labour'
import { Route as MyWorkRouteImport } from './routes/my-work'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SecretarialRouteImport } from './routes/secretarial'
import { Route as TaxRouteImport } from './routes/tax'
import { Route as EntitiesIndexRouteImport } from './routes/entities.index'
import { Route as EntitiesIdRouteImport } from './routes/entities.$id'
import { Route as ObligationsIndexRouteImport } from './routes/obligations.index'
import { Route as ObligationsIdRouteImport } from './routes/obligations.$id'
import { Route as QmsAuditsRouteImport } from './routes/qms.audits'
import { Route as QmsCapaRouteImport } from './routes/qms.capa'
import { Route as QmsDocumentsRouteImport } from './routes/qms.documents'
import { Route as QmsManagementReviewsRouteImport } from './routes/qms.management-reviews'
import { Route as QmsRisksRouteImport } from './routes/qms.risks'
import { Route as RegulatoryAlertsRouteImport } from './routes/regulatory.alerts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const EhsRoute = EhsRouteImport.update({
  id: '/ehs',
  path: '/ehs',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const LabourRoute = LabourRouteImport.update({
  id: '/labour',
  path: '/labour',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWorkRoute = MyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretarialRoute = SecretarialRouteImport.update({
  id: '/secretarial',
  path: '/secretarial',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxRoute = TaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesIndexRoute = EntitiesIndexRouteImport.update({
  id: '/entities/',
  path: '/entities/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesIdRoute = EntitiesIdRouteImport.update({
  id: '/entities/$id',
  path: '/entities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ObligationsIndexRoute = ObligationsIndexRouteImport.update({
  id: '/obligations/',
  path: '/obligations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObligationsIdRoute = ObligationsIdRouteImport.update({
  id: '/obligations/$id',
  path: '/obligations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QmsAuditsRoute = QmsAuditsRouteImport.update({
  id: '/qms/audits',
  path: '/qms/audits',
  getParentRoute: () => rootRouteImport,
} as any)
const QmsCapaRoute = QmsCapaRouteImport.update({
  id: '/qms/capa',
  path: '/qms/capa',
  getParentRoute: () => rootRouteImport,
} as any)
const QmsDocumentsRoute = QmsDocumentsRouteImport.update({
  id: '/qms/documents',
  path: '/qms/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const QmsManagementReviewsRoute = QmsManagementReviewsRouteImport.update({
  id: '/qms/management-reviews',
  path: '/qms/management-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const QmsRisksRoute = QmsRisksRouteImport.update({
  id: '/qms/risks',
  path: '/qms/risks',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatoryAlertsRoute = RegulatoryAlertsRouteImport.update({
  id: '/regulatory/alerts',
  path: '/regulatory/alerts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/calendar': typeof CalendarRoute
  '/command-center': typeof CommandCenterRoute
  '/ehs': typeof EhsRoute
  '/evidence': typeof EvidenceRoute
  '/labour': typeof LabourRoute
  '/my-work': typeof MyWorkRoute
  '/reports': typeof ReportsRoute
  '/secretarial': typeof SecretarialRoute
  '/tax': typeof TaxRoute
  '/entities/$id': typeof EntitiesIdRoute
  '/obligations/$id': typeof ObligationsIdRoute
  '/qms/audits': typeof QmsAuditsRoute
  '/qms/capa': typeof QmsCapaRoute
  '/qms/documents': typeof QmsDocumentsRoute
  '/qms/management-reviews': typeof QmsManagementReviewsRoute
  '/qms/risks': typeof QmsRisksRoute
  '/regulatory/alerts': typeof RegulatoryAlertsRoute
  '/entities/': typeof EntitiesIndexRoute
  '/obligations/': typeof ObligationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/calendar': typeof CalendarRoute
  '/command-center': typeof CommandCenterRoute
  '/ehs': typeof EhsRoute
  '/evidence': typeof EvidenceRoute
  '/labour': typeof LabourRoute
  '/my-work': typeof MyWorkRoute
  '/reports': typeof ReportsRoute
  '/secretarial': typeof SecretarialRoute
  '/tax': typeof TaxRoute
  '/entities/$id': typeof EntitiesIdRoute
  '/obligations/$id': typeof ObligationsIdRoute
  '/qms/audits': typeof QmsAuditsRoute
  '/qms/capa': typeof QmsCapaRoute
  '/qms/documents': typeof QmsDocumentsRoute
  '/qms/management-reviews': typeof QmsManagementReviewsRoute
  '/qms/risks': typeof QmsRisksRoute
  '/regulatory/alerts': typeof RegulatoryAlertsRoute
  '/entities': typeof EntitiesIndexRoute
  '/obligations': typeof ObligationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/calendar': typeof CalendarRoute
  '/command-center': typeof CommandCenterRoute
  '/ehs': typeof EhsRoute
  '/evidence': typeof EvidenceRoute
  '/labour': typeof LabourRoute
  '/my-work': typeof MyWorkRoute
  '/reports': typeof ReportsRoute
  '/secretarial': typeof SecretarialRoute
  '/tax': typeof TaxRoute
  '/entities/$id': typeof EntitiesIdRoute
  '/obligations/$id': typeof ObligationsIdRoute
  '/qms/audits': typeof QmsAuditsRoute
  '/qms/capa': typeof QmsCapaRoute
  '/qms/documents': typeof QmsDocumentsRoute
  '/qms/management-reviews': typeof QmsManagementReviewsRoute
  '/qms/risks': typeof QmsRisksRoute
  '/regulatory/alerts': typeof RegulatoryAlertsRoute
  '/entities/': typeof EntitiesIndexRoute
  '/obligations/': typeof ObligationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-assistant'
    | '/calendar'
    | '/command-center'
    | '/ehs'
    | '/evidence'
    | '/labour'
    | '/my-work'
    | '/reports'
    | '/secretarial'
    | '/tax'
    | '/entities/$id'
    | '/obligations/$id'
    | '/qms/audits'
    | '/qms/capa'
    | '/qms/documents'
    | '/qms/management-reviews'
    | '/qms/risks'
    | '/regulatory/alerts'
    | '/entities/'
    | '/obligations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai-assistant'
    | '/calendar'
    | '/command-center'
    | '/ehs'
    | '/evidence'
    | '/labour'
    | '/my-work'
    | '/reports'
    | '/secretarial'
    | '/tax'
    | '/entities/$id'
    | '/obligations/$id'
    | '/qms/audits'
    | '/qms/capa'
    | '/qms/documents'
    | '/qms/management-reviews'
    | '/qms/risks'
    | '/regulatory/alerts'
    | '/entities'
    | '/obligations'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-assistant'
    | '/calendar'
    | '/command-center'
    | '/ehs'
    | '/evidence'
    | '/labour'
    | '/my-work'
    | '/reports'
    | '/secretarial'
    | '/tax'
    | '/entities/$id'
    | '/obligations/$id'
    | '/qms/audits'
    | '/qms/capa'
    | '/qms/documents'
    | '/qms/management-reviews'
    | '/qms/risks'
    | '/regulatory/alerts'
    | '/entities/'
    | '/obligations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AiAssistantRoute: typeof AiAssistantRoute
  CalendarRoute: typeof CalendarRoute
  CommandCenterRoute: typeof CommandCenterRoute
  EhsRoute: typeof EhsRoute
  EvidenceRoute: typeof EvidenceRoute
  LabourRoute: typeof LabourRoute
  MyWorkRoute: typeof MyWorkRoute
  ReportsRoute: typeof ReportsRoute
  SecretarialRoute: typeof SecretarialRoute
  TaxRoute: typeof TaxRoute
  EntitiesIdRoute: typeof EntitiesIdRoute
  ObligationsIdRoute: typeof ObligationsIdRoute
  QmsAuditsRoute: typeof QmsAuditsRoute
  QmsCapaRoute: typeof QmsCapaRoute
  QmsDocumentsRoute: typeof QmsDocumentsRoute
  QmsManagementReviewsRoute: typeof QmsManagementReviewsRoute
  QmsRisksRoute: typeof QmsRisksRoute
  RegulatoryAlertsRoute: typeof RegulatoryAlertsRoute
  EntitiesIndexRoute: typeof EntitiesIndexRoute
  ObligationsIndexRoute: typeof ObligationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ehs': {
      id: '/ehs'
      path: '/ehs'
      fullPath: '/ehs'
      preLoaderRoute: typeof EhsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labour': {
      id: '/labour'
      path: '/labour'
      fullPath: '/labour'
      preLoaderRoute: typeof LabourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-work': {
      id: '/my-work'
      path: '/my-work'
      fullPath: '/my-work'
      preLoaderRoute: typeof MyWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secretarial': {
      id: '/secretarial'
      path: '/secretarial'
      fullPath: '/secretarial'
      preLoaderRoute: typeof SecretarialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax': {
      id: '/tax'
      path: '/tax'
      fullPath: '/tax'
      preLoaderRoute: typeof TaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/': {
      id: '/entities/'
      path: '/entities'
      fullPath: '/entities/'
      preLoaderRoute: typeof EntitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$id': {
      id: '/entities/$id'
      path: '/entities/$id'
      fullPath: '/entities/$id'
      preLoaderRoute: typeof EntitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obligations/': {
      id: '/obligations/'
      path: '/obligations'
      fullPath: '/obligations/'
      preLoaderRoute: typeof ObligationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obligations/$id': {
      id: '/obligations/$id'
      path: '/obligations/$id'
      fullPath: '/obligations/$id'
      preLoaderRoute: typeof ObligationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qms/audits': {
      id: '/qms/audits'
      path: '/qms/audits'
      fullPath: '/qms/audits'
      preLoaderRoute: typeof QmsAuditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qms/capa': {
      id: '/qms/capa'
      path: '/qms/capa'
      fullPath: '/qms/capa'
      preLoaderRoute: typeof QmsCapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qms/documents': {
      id: '/qms/documents'
      path: '/qms/documents'
      fullPath: '/qms/documents'
      preLoaderRoute: typeof QmsDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qms/management-reviews': {
      id: '/qms/management-reviews'
      path: '/qms/management-reviews'
      fullPath: '/qms/management-reviews'
      preLoaderRoute: typeof QmsManagementReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qms/risks': {
      id: '/qms/risks'
      path: '/qms/risks'
      fullPath: '/qms/risks'
      preLoaderRoute: typeof QmsRisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulatory/alerts': {
      id: '/regulatory/alerts'
      path: '/regulatory/alerts'
      fullPath: '/regulatory/alerts'
      preLoaderRoute: typeof RegulatoryAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AiAssistantRoute: AiAssistantRoute,
  CalendarRoute: CalendarRoute,
  CommandCenterRoute: CommandCenterRoute,
  EhsRoute: EhsRoute,
  EvidenceRoute: EvidenceRoute,
  LabourRoute: LabourRoute,
  MyWorkRoute: MyWorkRoute,
  ReportsRoute: ReportsRoute,
  SecretarialRoute: SecretarialRoute,
  TaxRoute: TaxRoute,
  EntitiesIdRoute: EntitiesIdRoute,
  ObligationsIdRoute: ObligationsIdRoute,
  QmsAuditsRoute: QmsAuditsRoute,
  QmsCapaRoute: QmsCapaRoute,
  QmsDocumentsRoute: QmsDocumentsRoute,
  QmsManagementReviewsRoute: QmsManagementReviewsRoute,
  QmsRisksRoute: QmsRisksRoute,
  RegulatoryAlertsRoute: RegulatoryAlertsRoute,
  EntitiesIndexRoute: EntitiesIndexRoute,
  ObligationsIndexRoute: ObligationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
